export const guestsQuantity = [
    '1 Person',
    '2 People',
    '3 People',
    '4 People',
    '5 People',
    '6 People',
    '7 People',
    '8 People',
    '8 People',
    '10 People',
    '11 People',
    '12 People',
    '13 People',
    '14 People',
    '15 People',
    '16 People',
    '17 People',
    '18 People',
    '19 People',
    '20 People',
    'Larger Party'
];